name = "HydrophoneCalibrations"
uuid = "13b29641-ba3c-435b-b4fe-906d24f049a9"
authors = ["Morten F. Rasmussen <10264458+mofii@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
Dierckx = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
